### ISSUE TITLE
gold fraction and trusted fraction

### ISSUE THREAD

**Issue by jisoolee0123** [mmazeika/glc#2]
Hi, thank you for sharing the code. 
I would be grateful if you could resolve my confusion.

I understand that 'gold_fraction' in your scripts is the same as 'trusted fraction' in your paper.
However, 'gold_fraction' is not the same as  'trusted fraction' in the following. 
https://github.com/mmazeika/glc/blob/5b456a0df468b972bcaa030730cf04d44c57910e/CIFAR/train_ours.py#L33

As stated in the paper (p.2), 'trusted fraction' is defined as (# of trusted samples) / (# of untrusted samples). And the following snippet is how to make trusted and untrusted datasets by the given 'gold_fraction'.

https://github.com/mmazeika/glc/blob/5b456a0df468b972bcaa030730cf04d44c57910e/CIFAR/load_corrupted_data.py#L101-L111

https://github.com/mmazeika/glc/blob/5b456a0df468b972bcaa030730cf04d44c57910e/CIFAR/load_corrupted_data.py#L119-L121

In the case where 'gold_fraction' is 0.5, 'trusted fraction' would be 1.0. 
Could you explain precisely how to generate trusted and untrusted datasets to reproduce the results in Section 4?

Thanks.

**Comment by mmazeika** [comment]
Hello, t/u is a typo in the paper that we will fix in the final version to t/(t+u). Thank you for pointing it out.
